pull_request_rules:
  - name: automatic merge for Dependabot pull requests on master
    conditions:
      - author~=dependabot(-preview)?\[bot\]
      - label~=dependencies
    actions:
      merge:
        method: squash
        strict: smart
  - name: automatic merge on CI success and review
    conditions:
      - label~=merge pull
    actions:
      merge:
        method: merge
        strict: smart
  - name: add WIP label when WIP is in title
    conditions:
      - title~=WIP
    actions:
      comment:
        message: Please remove WIP from the title. I have set the WIP Label for you instead.
      label:
        add:
          - WIP
  - name: delete merged branch
    conditions:
      - merged
    actions:
      delete_head_branch: {}
