branches:
  only:
    - master
language: node_js
node_js:
  - "lts/*"
script:
  - yarn lint
  - yarn build
notifications:
  email: false
cache: yarn
deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL_ADDRESS # Set in the settings page of your repository, as a secure variable
    api_key: $NPM_AUTH_TOKEN # Set in the settings page of your repository, as a secure variable
    tag: latest
    on:
      branch: master
  - provider: surge
    # Set SURGE_LOGIN and SURGE_TOKEN as secure variables
    skip_cleanup: true
    project: "dist/docs"
    domain: docs.vue-filter-ui.surge.sh
    on:
      branch: master
