language: node_js
node_js:
  - "lts/*"
script:
  - yarn lint
  - yarn build
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
notifications:
  email: false
cache:
  directories:
    - node_modules
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN
   on:
    branch: master
  tag: stable