branches:
  only:
    - master
    - /^greenkeeper/.*$/
language: node_js
node_js:
  - "lts/*"
script:
  - yarn lint
  - yarn build
notifications:
  email: false
cache:
  directories:
    - node_modules
deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL_ADDRESS # Set in the settings page of your repository, as a secure variable
    api_key: $NPM_AUTH_TOKEN # Set in the settings page of your repository, as a secure variable
    tag: latest
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local-dir: "dist/docs"
    allow-empty-commit: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
      branch: master
  - provider: surge
    # Set SURGE_LOGIN and SURGE_TOKEN as secure variables
    skip_cleanup: true
    project: "dist/docs"
    domain: docs.vue-filter-ui.surge.sh
    on:
      branch: master
